In [ ]:
import pypowsybl.network as pn
import pypowsybl as pp
from pypowsybl_jupyter import nad_explorer
import pandas as pd 
import importlib

In [2]:
from utils import extract_slack_info_for_nad, unique_list
from nad_explorer_slack import nad_explorer_with_slack
import nad_explorer_slack
import pypowsybl as pp
import utils
import importlib

In [3]:
importlib.reload(utils)
importlib.reload(nad_explorer_slack)

In [5]:
data = pd.read_csv(
   "Test_V_IEEE\ieee30\ieee30_voltage-perturbation.csv",
    sep=";",
    engine="python",
    index_col=False,
   # on_bad_lines="skip",
)
data.head()
len(data)
data["has_slack"] = data['slackValue'].notna()

<>:2: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
<>:2: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
C:\Users\slavine\AppData\Local\Temp\ipykernel_10384\2362266736.py:2: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
  "Test_V_IEEE\ieee30\ieee30_voltage-perturbation.csv",

In [6]:
data.head()

,busId,type,slackValue_pu,slackValue,gen,controlevoltage,transfo,shunt,load,load_violation,gen_violation,has_slack
0,VL2_0,V,-0.025754,-3.399494,B2-G,"VoltageControl(type=GENERATOR, controlledBus='...",NaN,NaN,VL2_0_load,0,0,True
1,VL6_0,V,0.026357,3.479183,NaN,"VoltageControl(type=GENERATOR, controlledBus='...",NaN,NaN,NaN,0,0,True

In [7]:
network = pp.network.load('Outputs\ieee30-voltage-perturbation.xiidm')
network.get_bus_breaker_view_buses()

<>:1: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
<>:1: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
C:\Users\slavine\AppData\Local\Temp\ipykernel_10384\4264096230.py:1: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
  network = pp.network.load('Outputs\ieee30-voltage-perturbation.xiidm')

,name,v_mag,v_angle,connected_component,synchronous_component,voltage_level_id,bus_id
id,,,,,,,
B1,Glen Lyn 132,139.920000,0.000000,0,0,VL1,VL1_0
B2,Claytor 132,134.540506,-11.846267,0,0,VL2,VL2_0
B3,Kumis 132,134.910997,-8.825771,0,0,VL3,VL3_0
B4,Hancock 132,133.845971,-10.891464,0,0,VL4,VL4_0
B12,Hancock 33,34.806035,-16.413658,0,0,VL12,VL12_0
B5,Fieldale 132,133.320000,-18.073271,0,0,VL5,VL5_0
B6,Roanoke 132,134.522183,-11.848076,0,0,VL6,VL6_0
B9,Roanoke 1.0,1.051440,-15.148190,0,0,VL9,VL9_0
B10,Roanoke 33,34.374445,-16.893388,0,0,VL10,VL10_0
B7,Blaine 132,132.978734,-14.914383,0,0,VL7,VL7_0
B8,Reusens 132,66.000000,-4.928776,0,0,VL8,VL8_0
B11,Roanoke 11,11.902000,-15.148190,0,0,VL11,VL11_0
B13,Hancock 11,11.781000,-16.413658,0,0,VL13,VL13_0
B14,Bus 14 33,34.259092,-17.277317,0,0,VL14,VL14_0
B15,Bus 15 33,34.060907,-17.299228,0,0,VL15,VL15_0
B16,Bus 16 33,34.376463,-16.877669,0,0,VL16,VL16_0
B17,Bus 17 33,34.207704,-17.106550,0,0,VL17,VL17_0
B18,Bus 18 33,33.768947,-17.857507,0,0,VL18,VL18_0
B19,Bus 19 33,33.700011,-17.995638,0,0,VL19,VL19_0
B20,Bus 20 33,33.842847,-17.777896,0,0,VL20,VL20_0
B21,Bus 21 33,33.855940,-17.332672,0,0,VL21,VL21_0
B22,Bus 22 33,33.839689,-17.314438,0,0,VL22,VL22_0
B23,Bus 23 33,33.488231,-17.558383,0,0,VL23,VL23_0
B24,Bus 24 33,33.003972,-17.553037,0,0,VL24,VL24_0
B25,Bus 25 33,31.725325,-16.627008,0,0,VL25,VL25_0
B26,Bus 26 33,31.106560,-17.097968,0,0,VL26,VL26_0
B27,Cloverdle 33,31.228851,-15.771069,0,0,VL27,VL27_0
B28,Cloverdle132,118.773835,-11.728485,0,0,VL28,VL28_0
B29,Bus 29 33,30.514342,-17.214131,0,0,VL29,VL29_0
B30,Bus 30 33,30.101342,-18.255775,0,0,VL30,VL30_0

In [ ]:
# data_grouped = data.groupby('busId')[['type','slackValue_pu','slackValue']].agg(unique_list)
# len(data_grouped)

In [8]:
# network = pp.network.load('Outputs/ieee300-1.xiidm')
slack_info = network.get_bus_breaker_view_buses().join(
    data.set_index("busId"),
    on="bus_id",
    how="left"
)
slack_info.reset_index(inplace=True)
slack_info

,id,name,v_mag,v_angle,connected_component,synchronous_component,voltage_level_id,bus_id,type,slackValue_pu,slackValue,gen,controlevoltage,transfo,shunt,load,load_violation,gen_violation,has_slack
0,B1,Glen Lyn 132,139.920000,0.000000,0,0,VL1,VL1_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B2,Claytor 132,134.540506,-11.846267,0,0,VL2,VL2_0,V,-0.025754,-3.399494,B2-G,"VoltageControl(type=GENERATOR, controlledBus='...",NaN,NaN,VL2_0_load,0.0,0.0,True
2,B3,Kumis 132,134.910997,-8.825771,0,0,VL3,VL3_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B4,Hancock 132,133.845971,-10.891464,0,0,VL4,VL4_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B12,Hancock 33,34.806035,-16.413658,0,0,VL12,VL12_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,B5,Fieldale 132,133.320000,-18.073271,0,0,VL5,VL5_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,B6,Roanoke 132,134.522183,-11.848076,0,0,VL6,VL6_0,V,0.026357,3.479183,NaN,"VoltageControl(type=GENERATOR, controlledBus='...",NaN,NaN,NaN,0.0,0.0,True
7,B9,Roanoke 1.0,1.051440,-15.148190,0,0,VL9,VL9_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,B10,Roanoke 33,34.374445,-16.893388,0,0,VL10,VL10_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,B7,Blaine 132,132.978734,-14.914383,0,0,VL7,VL7_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,B8,Reusens 132,66.000000,-4.928776,0,0,VL8,VL8_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,B11,Roanoke 11,11.902000,-15.148190,0,0,VL11,VL11_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,B13,Hancock 11,11.781000,-16.413658,0,0,VL13,VL13_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,B14,Bus 14 33,34.259092,-17.277317,0,0,VL14,VL14_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,B15,Bus 15 33,34.060907,-17.299228,0,0,VL15,VL15_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,B16,Bus 16 33,34.376463,-16.877669,0,0,VL16,VL16_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,B17,Bus 17 33,34.207704,-17.106550,0,0,VL17,VL17_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,B18,Bus 18 33,33.768947,-17.857507,0,0,VL18,VL18_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,B19,Bus 19 33,33.700011,-17.995638,0,0,VL19,VL19_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,B20,Bus 20 33,33.842847,-17.777896,0,0,VL20,VL20_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,B21,Bus 21 33,33.855940,-17.332672,0,0,VL21,VL21_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,B22,Bus 22 33,33.839689,-17.314438,0,0,VL22,VL22_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,B23,Bus 23 33,33.488231,-17.558383,0,0,VL23,VL23_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,B24,Bus 24 33,33.003972,-17.553037,0,0,VL24,VL24_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,B25,Bus 25 33,31.725325,-16.627008,0,0,VL25,VL25_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,B26,Bus 26 33,31.106560,-17.097968,0,0,VL26,VL26_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,B27,Cloverdle 33,31.228851,-15.771069,0,0,VL27,VL27_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,B28,Cloverdle132,118.773835,-11.728485,0,0,VL28,VL28_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,B29,Bus 29 33,30.514342,-17.214131,0,0,VL29,VL29_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,B30,Bus 30 33,30.101342,-18.255775,0,0,VL30,VL30_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Aggregate bus-level slack data to voltage level
slack_info_by_vl = slack_info.groupby('voltage_level_id').agg({
    'has_slack': 'any',  # Has slack if ANY bus in VL has slack
    'type': lambda x: list(x.dropna()),  # List of slack types in VL,
    'slackValue_pu': lambda x: list(x.dropna()),  # List of slack values in VL,
    'bus_id': lambda x: list(x.dropna().unique())  # List of bus IDs in VL
}).reset_index()

# Rename for compatibility
slack_info_by_vl.set_index('voltage_level_id', inplace=True)

slack_info_by_vl

                  has_slack type slackValue_pu    bus_id
voltage_level_id
VL1                   False   []            []   [VL1_0]
VL10                  False   []            []  [VL10_0]
VL11                  False   []            []  [VL11_0]
VL12                  False   []            []  [VL12_0]
VL13                  False   []            []  [VL13_0]
VL14                  False   []            []  [VL14_0]
VL15                  False   []            []  [VL15_0]
VL16                  False   []            []  [VL16_0]
VL17                  False   []            []  [VL17_0]
VL18                  False   []            []  [VL18_0]
VL19                  False   []            []  [VL19_0]
VL2                    True  [V]   [-0.025754]   [VL2_0]
VL20                  False   []            []  [VL20_0]
VL21                  False   []            []  [VL21_0]
VL22                  False   []            []  [VL22_0]
VL23                  False   []            []  [VL23_0]
VL24                  False   []            []  [VL24_0]
VL25                  False   []            []  [VL25_0]
VL26                  False   []            []  [VL26_0]
VL27                  False   []            []  [VL27_0]
VL28                  False   []            []  [VL28_0]
VL29                  False   []            []  [VL29_0]
VL3                   False   []            []   [VL3_0]
VL30                  False   []            []  [VL30_0]
VL4                   False   []            []   [VL4_0]
VL5                   False   []            []   [VL5_0]
VL6                    True  [V]    [0.026357]   [VL6_0]
VL7                   False   []            []   [VL7_0]
VL8                   False   []            []   [VL8_0]
VL9                   False   []            []   [VL9_0]

In [10]:
explorer = nad_explorer_with_slack(network, slack_info=slack_info_by_vl)

In [ ]:
explorer

HBox(children=(VBox(children=(Label(value='Voltage Levels'), Dropdown(description='Slack info:', options=('All…

In [ ]:
import pypowsybl.network as pn
from pypowsybl_jupyter import network_explorer, display_nad